#项目容器端口
server:
  port: 7000


spring:
  # 热部署静态文件
  thymeleaf:
    cache: false
  application:
    name: micro-weather-report

eureka:
  client:  #客户端注册进eureka服务器列表内
    service-url:
#      defaultZone: http://localhost:9000/eureka
      defaultZone: http://www.imxxm.top:9001/eureka/,http://www.imrose.top:9002/eureka/,http://www.itzw.top:9003/eureka/
  instance:
    instance-id: micro-report-provider7000   #自定义服务名称信息
    prefer-ip-address: true   #访问路径可以显示IP地址


